# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'IosCustomUiSdk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'Applozic'
   pod 'MessageKit'
   pod 'Kingfisher'

  target 'IosCustomUiSdkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IosCustomUiSdkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
