# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IosCustomUiSdk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'Applozic', '6.1.0'
   pod 'MessageKit'
   pod 'Kingfisher', '~> 4.7.0'

  target 'IosCustomUiSdkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IosCustomUiSdkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
